---
title: "복합시제(미래)"
date: 2019-10-09
date-modified: 2019-10-07
categories: [English, Grammar]
description: "미래표현, 미래진행, 미래완료"
---

## 미래표현
* **will, 단순현재, be going to, be to**

### will
1. 순수한 의미 예측 (그냥 아무 생각 없이)
    * It'[ll]{.underline} be spring soon.
    * You can call me this evening. I'[ll]{.underline} be at home.
    * Who do you think [will]{.underline} win on Saturday?
    * I [shall]{.underline} be rich one day.

2. 미래에 대한 의지 (intension)
    1. 말하는 **순간** 내리는 결정
        * A: The phone's ringing.
        * B: I'[ll]{.underline} answer it.

        * A. My bag is very heavy.
        * B: I'[ll]{.underline} carry it for you.
    2. 요청
        * [Will]{.underline} you open the door for me?

    3. 강한 의지나 의도
        * I'[ll]{.underline} hit you if you do that again.
        * You'[ll]{.underline} reget this.
        * I promise I [won't]{.underline} smoke again.
        * I'[ll]{.underline} buy you a computer for your birthday.

    4. "~할까요?"라는 제안 Shall I[we] ~?
        * [Shall]{.underline} I open a window?
        * [Shall]{.underline} we go for a swim?
        * Let's go and see Ryan, [Shall]{.underline} we?

### 단순현재
* 구체적인 일시가 이미 정해진 경우
    * What time [does]{.underline} the bus arrive in Seoul?
    * I [start]{.underline} my job next week.
    * [Are]{.underline} you on duty next Monday?
    * The conect [begins]{.underline} at 8.
    * The exhibition [opens]{.underline} on November 1. 
    * I'll call you when he [comes]{.underline} back.
    * I'll meet you there if it [rains]{.underline} tomorrow.

### be going to
1. 순수한 의미 예측 (will과 달리 판단할 수 있는 근거가 있음)
    * (시계를 보며) What? It's already 4 o'clock? I'[m going to]{.underline} be late.
    * (배가 불룩한 임산부를 보며) She'[s going to]{.underline} have a baby soon.
    * (한뜩 흐린 하늘을 보며) Look at the sky. It'[s going to]{.underline} rain.

2. 미래에 대한 의지 (현재진행 형태도 사용 가능)
    * 현재 이미 결정이나 계획이 돼 있는 경우, 또는 어느 정도 미리 시작돼 있는 상태
        * 현재진행
            * A: What [are]{.underline} you [doing]{.underline} this evening?
            * B: I'[m going]{.underline} to a party.

            * We'[re going]{.underline} to Eruope this summer.
            * I'[m seeing]{.underline} Ryan on Saturday. 
        
        * be going to
            * We'[re going to]{.underline} get a new car soon.
            * I'[m going to]{.underline} keep asking her out until she says 'yes'.
        
### be to
* 고상하고 우아한 문체, 공식적인 발표, 신문에서 주로 사용됨
* 이미 예정 또는 계획된 일
    * The President [is to visit]{.underline} Japan next month.

### 과거에서 본 미래
* Last time I saw you, you [were going to]{.underline} start a new job. (be going to)
* I didn't have much time to talk to Ryan because I [was leaving]{.underline} for Germany in two hours. (현재진행)
* In 1967, I arrived in the town where I [would]{.underline} spend the next ten years of my life. (will)
* I felt nervous because I [was]{.underline} soon [to leave]{.underline} home for the first time. (be to)

### 미래를 표현하는 일반 동사들
* I [hope]{.underline} to see you next month. (hope)
* Here's what I'm [planning]{.underline} to get. (plan)
* The movie [is about to]{.underline} begin. (be about to)

## 미래진행
### 미래 한 시점에서 진행중인 상황
* This time tomorrow I'[ll be flying]{.underline} to New York.
* Hurry Up! The guests [will be arriving]{.underline} at any minute.

### 진행의 의미가 없을 수도 있음 (**약한 의지 표현**)
* I'[ll]{.underline} see you tomorrow. (강한 의지)
* I'[ll be seeing]{.underline} you one of these days. (약한 의지)

* Well, exactly when [will]{.underline} you get the job done? (강한 의지)
* When [will]{.underline} you [be finishing]{.underline} it, sir? (약한 의지)
* How long [will]{.underline} you stay? (permanent, 이사, 이민 등)
* How long [will]{.underline} you [be staying]{.underline}? (temporary, 입국 심사 등)

### 미래표현 vs. 미래완료
* 미래표현: 하염없이 미래로 날아가는 것
* 미래완료: 미래의 어느 한 시점까지라는 종착점이 있음
    * I'[ll leave]{.underline} tomorrow. (미래표현, 앞으로 ~하겠다)
    * I'[ll have left]{.underline} by tomorrow. (미래완료, 앞으로 어느 시점이 되면 ~하게 돼 있을 거다)

### by 표현과 함께 주로 많이 사용
* By next Christmas we'[ll have been]{.underline} here for ten years.   
* By the time you read this, I'[ll have left]{.underline}.

### 미래의 한 시점에서의 의미나 결과에 주안점을 두고 있는 상태 (종착점이 있음)
* I will read this book three times. (앞으로 ~하겠다)
* I will have read this book three times by next Wednesday. (앞으로 어느 시점이 되면 ~하게 돼 있을 거다)

### **미래완료는 동작이 언제 이루어지는가는 중요치 않고, 미래의 한 시점에서의 의미나 결과에 주안점을 두는 표현**
* I [will have read]{.underline} this book three times if I read it once more.

*** 

* Reference: 
    * 오성호. (2006). *Again! 뒤집어본 영문법*. 김영사.
